### ISSUE TITLE
String() wraps with curly braces

### ISSUE THREAD

**Issue by tschundeee** [twinj/uuid#10]
Hi, when I use something like:

hash := uuid.NewV4().String()

then I the uuid wrapped with curly braces. I don't want this behavior when I use String(). Is this intentionally done this way? All the other uuid libraries export the plain alphanumeric uuid.

**Comment by prep** [comment]
Try this:

```go
uuid.SwitchFormat(uuid.CleanHyphen)
uuid.NewV4().String()
```

**Comment by chrissnell** [comment]
+1 to @tschundeee.  I expected a CleanHyphen format, too, and had to read the source to figure out what was going on.  Maybe CleanHyphen could be the default, since that's what [many people think of](https://www.uuidgenerator.net/version4) when they want a UUID.

Also--and this is a tiny nitpick--the README links to the GoDocs and mentions examples but there really aren't any examples in there.  It's easy enough to figure out but maybe a simple V4 CleanHyphen generator example would help the newbs.

**Comment by twinj** [comment]
Could definitely do with some housekeeping and better examples. I think changing the format to cleanHyphen is the correct way too. Should have been this to begin with.
