### ISSUE TITLE
SwitchFormat

### ISSUE THREAD

**Issue by DavidVaini** [twinj/uuid#14]
You changed it in the last commit from a Public Method to a Private method here:
https://github.com/twinj/uuid/commit/c919ceb3ab30b26eb5be6ec40141a9f0cb73c034#diff-8f82f8f5d16bc60b0c3c0d722c03194bR245

This is breaking a lot of code that uses your library, did you mean to do this for some reason? If so what is now the right way to implement it?

looks like you would use: uuid.SetStringerFormat(uuid.CleanHyphen) as an example.

**Comment by twinj** [comment]
Didn't mean to close this.

**Comment by twinj** [comment]
It was intentional, probably should have left it though, as the default format changed. I believe most people are using SwitchFormat to switch to uuid.CleanHyphen which is now the default. Remove the line if you fall in this use case. I felt SwitchFormat was not explanatory enough for new users hence the name change. I suppose it doesn't hurt to keep it public so the API remains the same. 

Probably getting to a point where I need to propose changes instead of just making them. Thanks for reporting this.
